server:
  port: 8443
  context-path: /cademo
  ssl:
    key-store: classpath:certs/server.keystore
    key-store-password: 111111
    key-password: 111111
    key-alias: server
    trust-store: classpath:certs/server.keystore
    trust-store-password: 111111
    client-auth: need
logging:
  config: classpath:logback-spring.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS